### PR TITLE
SSH-Proxy tutorial

### PR DESCRIPTION
**Pull request by vonloxley**
In German, I was surprised by the decision to focus on English tutorials. If it meets your definition of 'great', great, if not, no problem.

I have read and understood the Contributor's Certificate of Origin at the end of the template and I hereby certify that I meet the contribution criteria described in it.

Signed-off-by: Niki Hansche <mf-developing@hansche.de>

### CODE REVIEW

**Comment by vonloxley** [comment]
Hi!

Thank you very much for the great translation!

I only have one minor request: Could w change
`, which allows to use SSH c`  to `, which allows using SSH c` in the first paragraph?

And I think in „Requirements“ `Since the presented technique is optimized to shorten deployment times from days to a few weeks,` should be: `Since the presented technique is optimized for short deployment times from days to a few weeks,`

Should `Therefore, it is called (SOCKS) proxy server is specified as localhost (see figure).` in step 4 be `Therefore, it is specified as localhost (see figure).`?

Again: Thanks for the great work!

**Comment by netcupClaudiaM** [comment]
Hi, 

please be so kind to adapt the tutorial file yourself to the needs/wishes you have and re-submit it. 
Thank you!

**Comment by vonloxley** [comment]
Sure! Would you give me the markdown-formatted document?

**Comment by netcupClaudiaM** [comment]
That´s not necessary :) You can implement the changes in your forked repo. For that just open up the Merge Request, edit your file and re-submit your tutorial.

**Comment by vonloxley** [comment]
Hi Claudia!

I’m not sure that we’re talking about the same things here. Would you help me clarify things, please?

1. d-schaffer had requested some changes. They are already part of my fork and of this pull-request. If I have to do anything more with them, I need a pointer.
2. d-schaffer requested my comments on the English translation (https://github.com/netcup-community/community-tutorials/pull/11#pullrequestreview-792841020), which I gave.
3. You asked me to implement those changes myself, which would be no problem for me. However, the translation exists only as a comment in this thread. I expect that they should end up in a file `01-en.md`. That file is in neither your nor my repo. I kindly request the markdown sources, so that I can incorporate my change requests. Again, if I can find the markdown-file somewhere, I need a pointer.

Kind regards!

**Comment by killerbees19** [comment]
@vonloxley Open the comment in your browser…

[https://github.com/netcup-community/community-tutorials/pull/11#pullrequestreview-792841020](https://github.com/netcup-community/community-tutorials/pull/11#pullrequestreview-792841020)

Now click at the _meatballs menu_ and select **Quote reply**. The markdown content of the comment should be visible at the editor. Just remove the `>` from each line.

**Comment by vonloxley** [comment]
That was "von hinten durch die Brust ins Auge". But it’s done now.

**Pull request merged**
