### PR TITLE
Added tutorial for DDNS with webhosting

### PR DESCRIPTION
**Pull request by LawGain**
I have read and understood the Contributor's Certificate of Origin at the end of the template and I hereby certify that I meet the contribution criteria described in it.

Signed-off-by: Jewgeni Lewash (j.lewash@gmail.com)

### CODE REVIEW

**Comment by raphi-0901** [comment]
Hey,
how can I test if it is working or not?

**Comment by LawGain** [comment]
That's a good question. For testing, there should be a server at home, otherwise, of course, a Netcup VPS also works, but the IP address does not change there.

First, a new script must be created on the server:
`nano update-ddns.sh`

Then you add the update script:
```
#!/usr/bin/env bash

USER="username as in the .env file"
PASS="password as in the .env file"
DOMAIN="example.com"
SCRIPT="https://example.com/update.php"
FORCE=0
MODE="@" # can be undefined, "@", "*" or "both"

IPV4=$(curl -4 -q v4.ident.me)
IPV6=$(curl -6 -q v6.ident.me)

echo ${IPV4}
echo ${IPV6}

# PAYLOAD_IPV4="force=${FORCE}&user=${USER}&password=${PASS}&ipv4=${IPV4}&domain=${DOMAIN}&mode=${MODE}"
# curl -X POST --data "${PAYLOAD_IPV4}" ${SCRIPT}

# PAYLOAD_IPV6="force=${FORCE}&user=${USER}&password=${PASS}&ipv6=${IPV6}&domain=${DOMAIN}&mode=${MODE"}
# curl -X POST --data "${PAYLOAD_IPV6}" ${SCRIPT}

PAYLOAD_BOTH="force=${FORCE}&user=${USER}&password=${PASS}&ipv4=${IPV4}&ipv6=${IPV6}&domain=${DOMAIN}&mode=${MODE}"
curl -X POST --data "${PAYLOAD_BOTH}" ${SCRIPT}
```

Then you run the script:
`sh update-ddns.sh`

The output should be:
```
[DEBUG] api login successful
[DEBUG] IPv4 for @.example.com set to 123.456.123.456
[DEBUG] dns recordset updated
[DEBUG] api logout successful
```

In the DNS settings in the CCP you can verify, that the DNS has been updated.

**Comment by raphi-0901** [comment]
I tried simply to call the update script from my browser but I´m getting a response of `File not found`

**Comment by LawGain** [comment]
First of all, unfortunately, it will not work this way. However, another error message should pop up when debug mode is on and ddns.mydomain.com/update.php is called:

`Fatal error: Uncaught RuntimeException: payload invalid in /var/www/vhosts/hosting123456.a2feb.netcup.net/ddns.mydomain.com/src/Handler.php:35 [...]`

Could you please put an index.html with any content in the working directory of the domain and call the domain without subdirectory (i.e. ddns.mydomain.com)? Will the content of the HTML file be shown?

**Comment by raphi-0901** [comment]
No this index.html is not shown.

**Comment by LawGain** [comment]
Please check the following:

1. You created a subdomain in your panel
2. The IP-address shown in the panel in the panel is the same as when you open any terminal and ping the subdomain
3. Open the hosting settings of the subdomain and verify, that the document root is the one where you put the index.html
4. Enable PHP support if you disabled it

I suspect that your DNS settings are not correct, if not even the index.html can be called.

**Comment by raphi-0901** [comment]
Yes, you were right. The subdomain had an incorrect IP address. I fixed that, but when I try to run the script, I get the following.
```
root@v220211184008168213:~# sh update-ddns.sh
202.61.232.52
2a03:4000:30:f742::16:4471
[DEBUG] api login failed, message: For this user the provided API key is not valid.

Notice: Trying to get property 'apisessionid' of non-object in /var/www/vhosts/hosting164471.ae834.netcup.net/abc.ncct-38.de/src/Handler.php on line 120

Notice: Trying to get property 'dnsrecords' of non-object in /var/www/vhosts/hosting164471.ae834.netcup.net/abc.ncct-38.de/src/Handler.php on line 127

Warning: Invalid argument supplied for foreach() in /var/www/vhosts/hosting164471.ae834.netcup.net/abc.ncct-38.de/src/Handler.php on line 127
[DEBUG] dns recordset NOT updated (no changes)

Notice: Trying to get property 'apisessionid' of non-object in /var/www/vhosts/hosting164471.ae834.netcup.net/abc.ncct-38.de/src/Handler.php on line 179
[DEBUG] api logout failed, message: For this user the provided API key is not valid.
```

**Comment by LawGain** [comment]
I'm happy that the script is now executing something. You should now check your API in the .env file seems like the data is wrong or you are not permitted to change dns settings with your API.

Maybe you could try to generate a new api key and enter the value into the env? Please make sure that the htaccess doesn't allow to open the env-file.

**Comment by raphi-0901** [comment]
Nice, now it works. I messed up something with the API key and the associated password.

**Comment by LawGain** [comment]
I plan to integrate a small troubleshooting at the weekend.

**Comment by netcupClaudiaM** [comment]
Hi LawGain, thank you for contributing! It's been a while since you opened this PR and it probably is an open secret we're currently overwhelmed with reviewing all the awesome tutorials we got. Please be patient - we're about to publish tutorials this and next week. Thank you!

**Pull request merged**
