### PR TITLE
New tutorial: Setup Wiki.js 2.x on netcup webhosting with MySQL backend

### PR DESCRIPTION
**Pull request by Copro**
Adding a documentation on how to setup the WikiJS wiki software with MySQL backend on netcup Webhosting packages with Node.js support > Webhosting 4000.
As mentioned on the netcup forums the setup might be interesting to some users but is not straight forward for most because of the plesk Phusion Node.js implementation.

https://forum.netcup.de/administration-eines-server-vserver/server-konfiguration/plesk/p212302-wiki-js-mit-plesk-onyx/#post212302

### CODE REVIEW

**Comment by stecklars** [comment]
Dear @Copro,

Thank you for your submission of a netcup community tutorial.

My name is Lars-Sören Steck and I am a Community Manager at netcup.

First of all, I would like to thank you for your patience, while we were reviewing this tutorial. We review these tutorials in a two step process: First, a technical review is performed, then a stylistic and syntactical review.

I have done the technical review. From a technical point of view, your tutorial indeed allows a reader to successfully install Wiki.js on a netcup Webhosting product.

I have noticed the following technical points, that I would kindly like to ask you to improve, before we proceed:

* The document root should not be determined at "PHP Settings", as this is the full path, that is not needed later on in the tutorial. We rather need the path starting from the `/` directory of the webspace. This path can be seen in the domain overview at the bottom (where all the buttons like "Node.js" are).
* Instead of directly linking to the database page in the Webhosting product, we would prefer a textual description of the way to get there (via "Databases" in the right sidebar).
* The WikiJS download link links to Roundcube.
* In the screenshot `netcup_wcp_activate_Node_js_support_wikijs_example_com_en-US.png` you may want to change the domain in the headline as well.

Please also change the following, so that we can proceed:
* The author image leads to a 404 page.

Once again, thank you for your work and we are looking forward to merging this after this has been addressed.

**Comment by Copro** [comment]
Thank you for the thorough review. I have made all the suggested changes and added a notice about switching from testing to production mode for Node.JS after testing the setup.

**Comment by stecklars** [comment]
@Copro Thank you for your Community Tutorial submission. We successfully reviewed it and have just merged it. The tutorial will show up on our Community Tutorial website as soon as possible (the page is regularly updated).

We will get back to you about the coupon. I have forwarded your contact information to the responsible department, so you should receive your coupon within the coming days.

**Comment by stecklars** [comment]
@Copro Your tutorial is live now, thanks once again! :)
https://community.netcup.com/en/tutorials/install-wikijs-on-webhosting

**Pull request merged**
