### PR TITLE
optimized installation (pufferpanel)

### PR DESCRIPTION
**Pull request by 2020Sanoj**
This PR makes the tutorial a little easier

### CODE REVIEW

**Comment by raphi-0901** [comment]
Hey @2020Sanoj, I´m not able to connect to Pufferpanel via IP. With domain, it works as expected.

**Comment by 2020Sanoj** [comment]
> Hey @2020Sanoj, I´m not able to connect to Pufferpanel via IP. With domain, it works as expected.

Do you have the Port open?

**Comment by raphi-0901** [comment]
Of course! It´s working now. I had to redefine my firewall rule.

**Comment by 2020Sanoj** [comment]
I have added an additional and optional part to the tutorial which shows how to give pufferpanel acces to docker

**Pull request merged**
