### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by phillipunzen**
I have read and understood the Contributor's Certificate of Origin at the end of the template and I hereby certify that I meet the contribution criteria described in it.

Make sure that you have your email address visible on your Github account. If your tutorial is accepted, you will receive an email from our netcup Community Team asking for your netcup Customer-ID, so the reward can be processed.

### CODE REVIEW

**Review by phillipunzen — COMMENTED** [review]
The tutorial is finished. 
You can install bookstack with this tutorial.

**Comment by phillipunzen** [comment]
You need some more Information from me? Or where do we go from here? @netcupChristophW

**Comment by netcupChristophW** [comment]
Hey, thank you very much for your contribution. I have done an initial review and tested that everything is in order. Your tutorial has now been handed over to our second reviewer team which are going to process it as quickly as possible. This may take a few additional days. I am sorry for any inconvenience this may cause. Regards, @netcupChristophW

**Comment by netcupChristophW** [comment]
Thank you very much for your submission, it has just been finally reviewed and was accepted into our repository. I have forwarded your information and you should receive a voucher within the coming days.

**Pull request merged**
