### PR TITLE
Add tutorial how to generate self signed openssl certificate and use it with nginx

### PR DESCRIPTION
**Pull request by PatrickWe**
I have read and understood the Contributor's Certificate of Origin at the end of the template and I hereby certify that I meet the contribution criteria described in it.

Signed-off-by: (Patrick Weber, netcup_wiki@icloud.com)

### CODE REVIEW

**Comment by netcupClaudiaM** [comment]
Hi PatrickWe, thank you for contributing! It's been a while since you opened this PR and it probably is an open secret we're currently overwhelmed with reviewing all the awesome tutorials we got. Please  be patient - we're about to publish tutorials this and next week. Thank you!

**Comment by raphi-0901** [comment]
Hey @PatrickWe, as you see there is a conflict which I´m not able to resolve. Please resolve the conflict by your own. If you are also not able to resolve it, just open a new PR with the latest state.

**Comment by PatrickWe** [comment]
conflicts are resolved now

**Comment by PatrickWe** [comment]
Please delete all of my opened pull requests. It is outrageous, that vouchers are not allowed for more than the half of your products. Shame on you.

**Pull request closed without merging**
