### PR TITLE
Add standalone Seafile Docker tutorial

### PR DESCRIPTION
**Pull request by maxkratz**
This PR adds a tutorial on how to set up a standalone [Seafile server](https://www.seafile.com/en/home/) including a valid LetsEncrypt certificate for TLS/SSL secured HTTPS connections.

Please notice that the linked tutorial on how to install Docker and Docker-Compose is not merged yet (https://github.com/netcup-community/community-tutorials/pull/17).

---

I have read and understood the Contributor's Certificate of Origin at the end of the template and I hereby certify that I meet the contribution criteria described in it.

Signed-off-by: Max Kratz <account@maxkratz.com>

### CODE REVIEW

**Comment by netcupClaudiaM** [comment]
Hi maxkratz, thank you for contributing! It's been a while since you opened this PR and it probably is an open secret we're currently overwhelmed with reviewing all the awesome tutorials we got. Please  be patient - we're about to publish tutorials this and next week. Thank you!

**Comment by maxkratz** [comment]
@netcupClaudiaM Thank you for the update! Take the time you need for all the reviews :).

**Comment by raphi-0901** [comment]
Hey @maxkratz, could you please upload all your pictures in english so that everything is consistent? Thanks!

**Comment by maxkratz** [comment]
@raphi-0901 No problem, I've fixed the German screenshots. Thank you for the suggestion.

Furthermore, I've added a configuration option for the services to automatically start in case the system had to be (re-)booted.

**Pull request merged**
