### PR TITLE
Install NodeJS with NPM

### PR DESCRIPTION
**Pull request by l3nnartt**
I have read and understood the Contributor's Certificate of Origin at the end of the template and I hereby certify that I meet the contribution criteria described in it.

Signed-off-by: Lennnart Lösche | <info@lennartloesche.de>

### CODE REVIEW

**Comment by d-schaffer** [comment]
I am sorry, @l3nnartt 
unfortunately your text is a bit too short ...
Could you expand the tutorial a bit or go more into depth?
Can you think of anything else? e.g. setting up a live environment...

**Review by d-schaffer — CHANGES_REQUESTED** [review]
I am sorry, @l3nnartt
unfortunately your text is a bit too short ...
Could you expand the tutorial a bit or go more into depth?
Can you think of anything else? e.g. setting up a live environment...

**Comment by l3nnartt** [comment]
Hey @d-schaffer , i added something, can you open the merge request again? :)

**Comment by l3nnartt** [comment]
image
Something is wrong here

**Comment by d-schaffer** [comment]
@l3nnartt , oh, you're right...
I'm sorry to tell you that your branch has been overwritten by our main branch.
You should please make a new PR, ideally you should also make your own branch and not work on the main.
and then make a PR from your branch to our main.

**Pull request merged**
