### PR TITLE
Add tutorial: How to install swift in Ubuntu 20.04

### PR DESCRIPTION
**Pull request by iWECon**
I have read and understood the Contributor's Certificate of Origin at the end of the [template](https://github.com/netcup-community/community-tutorials/blob/main/TEMPLATE.md) and I hereby certify that I meet the contribution criteria described in it.

### CODE REVIEW

**Comment by netcupClaudiaM** [comment]
Hello @iWECon, 
I just wanted to inform you that we will need some more time to process this review due to vacations and sick leaves. We hope for your understanding and will get in touch as soon as possible!
Kind regards, 
Claudia H.

**Comment by netcupChristophW** [comment]
Thank you very much for your patience @iWECon. Your tutorial has undergone a final review and was merged into the repository. I have forwarded your contact information to the responsible department, so you should receive your coupon within the coming days. Regards @netcupChristophW

**Comment by iWECon** [comment]
Thank you sir :)

**Comment by netcupChristophW** [comment]
Hey dear @iWECon, thanks for getting back to me. I've just checked with the responsible department and you should have received a voucher on the 9th of October 2023 at around 11:50 AM CET. Could you please check whether you have received an email at that point in time and date, also looking into your Spam Folder at that point in time? Thank you and Regards,
@netcupChristophW

**Comment by iWECon** [comment]
> Hey dear @iWECon, thanks for getting back to me. I've just checked with the responsible department and you should have received a voucher on the 9th of October 2023 at around 11:50 AM CET. Could you please check whether you have received an email at that point in time and date, also looking into your Spam Folder at that point in time? Thank you and Regards, @netcupChristophW

I'm so sorry, I've checked my inbox and spam and I've confirmed that I've lost the voucher message (I cleaned out the spam a while ago and I've tried to recover it but only up to 7 days), can your resend an email?
@netcupChristophW 

image
image
image

**Comment by netcupChristophW** [comment]
Dear @iWECon, I have forwarded the respective coupon mail a second time. Could you please check whether everything has been received? Regards, @netcupChristophW

**Comment by iWECon** [comment]
> Dear @iWECon, I have forwarded the respective coupon mail a second time. Could you please check whether everything has been received? Regards, @netcupChristophW 

Thank you sir, I saw the code~ :)

**Pull request merged**
