### PR TITLE
Tutorial - Install Chrome Remote Desktop on Your Netcup Server

### PR DESCRIPTION
**Pull request by Nishantbhagat57**
I have read and understood the Contributor's Certificate of Origin at the end of the [template](https://github.com/netcup-community/community-tutorials/blob/main/TEMPLATE.md) and I hereby certify that I meet the contribution criteria described in it.

My email: nishantbhagat57@gmail.com

### CODE REVIEW

**Comment by Nishantbhagat57** [comment]
Can you review this? @netcupChristophW 
Thanks & Regards,
Nishant

**Comment by netcupChristophW** [comment]
@Nishantbhagat57 Thank you for contributing a tutorial. I have forwarded the tutorial to our internal process and will ensure that it is processed as quickly as possible.

**Comment by Nishantbhagat57** [comment]
Hi @netcupChristophW, I was wondering if there is any update on my tutorial submission? Thanks, Nishant

**Comment by netcupChristophW** [comment]
Hi @Nishantbhagat57, Thank you for your request and once again, thank you for your contribution. At this point, your tutorial is currently undergoing a second review. We now have all tutorials reviewed by two members of different teams to ensure that both the language and content are a good fit for our community tutorials. This process should be completed in the coming days.

Again, I apologize for any inconvenience this may cause. Regards, @netcupChristophW

**Comment by netcupChristophW** [comment]
Thank you very much for your submission, it has just been finally reviewed and was accepted into our repository. I have forwarded your information and you should receive a voucher within the coming days.

**Pull request merged**
