### PR TITLE
AMS-9968: update links and text

### PR DESCRIPTION
**Pull request by TatjanaR2610**
https://ats.anexia-it.com/browse/AMS-9968

### CODE REVIEW

**Comment by vdbhb59** [comment]
I believe you should not have done this. The product links are correct as already available. Only in the en ones you should have made the changes. The de ones is breaking otherwise.

**Comment by lukas-kreuzer** [comment]
@vdbhb59 Why should we not have done this? These are the new product links that come with the .com website. I have checked all the links and they work fine.

**Review by lukas-kreuzer — APPROVED** [review]

**Comment by vdbhb59** [comment]
DE ones should be changed as per the language. I am not saying not to do it, but just changing the links makes no sense for the German language ones. Those are not rendering the language fully.

**Comment by lukas-kreuzer** [comment]
@vdbhb59 Sorry but I dont understand what you mean by that. What exactly does "not rendering the language fully" mean?

**Pull request merged**
