### PR TITLE
added ubuntu-debian-add-custom-dns

### PR DESCRIPTION
**Pull request by Tobi-dev**
Had the problem directly when i received my server.
Very basic stuff but probably it helps some people.

regards,

Tobi

### CODE REVIEW

**Comment by Tobi-dev** [comment]
Added a Kubernetes install tutorial aswell.

**Comment by raphi-0901** [comment]
Hey, please read our [contributing guidelines](https://github.com/netcup-community/community-tutorials/blob/main/CONTRIBUTING.md#how-to) carefully, especially the section `How To`.
You also have to include the sections `License` and `Contributor's Certificate of Origin` in your tutorial.

**Comment by raphi-0901** [comment]
> Added a Kubernetes install tutorial aswell.
> 
> Signed-off-by: Tobias Läpple [tobias.laepple92@gmail.com](mailto:tobias.laepple92@gmail.com)

Hey, if you want to submit another tutorial, you have to raise a separate PR for it.

**Comment by raphi-0901** [comment]
Hey, I'm going to close this PR now since you're not responding. However, you can create new PRs if you want.

**Pull request closed without merging**
